# Generated by Django 4.0.1 on 2022-04-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0002_stackedexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamplePdfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='', verbose_name='Pdf')),
                ('pdf2', models.FileField(upload_to='', verbose_name='Pdf 2')),
                ('pdf3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Pdf 3')),
            ],
            options={
                'verbose_name': 'Example Pdf Model',
                'verbose_name_plural': 'Example Pdf Models',
            },
        ),
        migrations.CreateModel(
            name='StackedPdfExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Example')),
                ('text', models.TextField(verbose_name='Text')),
                ('pdf', models.ImageField(upload_to='', verbose_name='Pdf')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplepdfmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModelPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='', verbose_name='Pdf')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplepdfmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnotherModalPdfsExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='', verbose_name='Pdf')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplepdfmodel')),
            ],
        ),
    ]
