# Generated by Django 4.0.1 on 2022-04-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_application', '0003_examplepdfmodel_stackedpdfexample_examplemodelpdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleAudioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio')),
                ('audio2', models.FileField(upload_to='', verbose_name='Audio 2')),
                ('audio3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio 3')),
            ],
            options={
                'verbose_name': 'Example Audio Model',
                'verbose_name_plural': 'Example Audio Models',
            },
        ),
        migrations.CreateModel(
            name='ExampleVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Video')),
                ('video2', models.FileField(upload_to='', verbose_name='Video 2')),
                ('video3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Video 3')),
            ],
            options={
                'verbose_name': 'Example Video Model',
                'verbose_name_plural': 'Example Video Models',
            },
        ),
        migrations.CreateModel(
            name='StackedVideoExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Example')),
                ('text', models.TextField(verbose_name='Text')),
                ('video', models.ImageField(upload_to='', verbose_name='Video')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplevideomodel')),
            ],
        ),
        migrations.CreateModel(
            name='StackedAudioExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Example')),
                ('text', models.TextField(verbose_name='Text')),
                ('audio', models.ImageField(upload_to='', verbose_name='Audio')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.exampleaudiomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModelVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Video')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplevideomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleModelAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='', verbose_name='Audio')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.exampleaudiomodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnotherModalVideosExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='Video')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.examplevideomodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnotherModalAudiosExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='', verbose_name='Audio')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_application.exampleaudiomodel')),
            ],
        ),
    ]
